version: "3.8"

services:
  node1:
    build: .
    container_name: blockchain-node1
    environment:
      NODE_ID: node1
      IS_LEADER: "true"
      PEERS: node2:50051,node3:50051
    ports:
      - "50051:50051"
      - "8080:8080"
    volumes:
      - node1_data:/app/data
    networks:
      - blockchain-network

  node2:
    build: .
    container_name: blockchain-node2
    environment:
      NODE_ID: node2
      IS_LEADER: "false"
      PEERS: node1:50051,node3:50051
    ports:
      - "50052:50051"
      - "8081:8080"
    volumes:
      - node2_data:/app/data
    networks:
      - blockchain-network
    depends_on:
      - node1

  node3:
    build: .
    container_name: blockchain-node3
    environment:
      NODE_ID: node3
      IS_LEADER: "false"
      PEERS: node1:50051,node2:50051
    ports:
      - "50053:50051"
      - "8082:8080"
    volumes:
      - node3_data:/app/data
    networks:
      - blockchain-network
    depends_on:
      - node1

volumes:
  node1_data:
  node2_data:
  node3_data:

networks:
  blockchain-network:
    driver: bridge
